// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MockServerVariableService.proto

package org.yefei.qa.mock.grpc.idl;

public interface VariableDefineRespOrBuilder extends
        // @@protoc_insertion_point(interface_extends:mock.server.grpc.VariableDefineResp)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool success = 1;</code>
     */
    boolean getSuccess();
}
