// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MockServerVariableService.proto

package org.yefei.qa.mock.grpc.idl;

public interface VariableOrBuilder extends
        // @@protoc_insertion_point(interface_extends:mock.server.grpc.Variable)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    String getName();

    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>optional string value = 2;</code>
     */
    String getValue();

    /**
     * <code>optional string value = 2;</code>
     */
    com.google.protobuf.ByteString
    getValueBytes();
}
