// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crmOrderService.proto

package org.yefei.qa.mock.grpc.idl;

public interface TPInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.msg.TPInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *  orderID
   * </pre>
   *
   * <code>optional int64 orderID = 1;</code>
   */
  long getOrderID();

  /**
   * <code>optional int64 orderKey = 2;</code>
   */
  long getOrderKey();

  /**
   * <code>optional string shopOrderKey = 3;</code>
   */
  java.lang.String getShopOrderKey();
  /**
   * <code>optional string shopOrderKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getShopOrderKeyBytes();
}
