// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crmOrderService.proto

package org.apache.skywalking.apm.mock.plugin.grpc.v1.core.idl;

public final class CrmOrderService {
    private CrmOrderService() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_msg_TPRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_msg_TPRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_proto_msg_TPInfoReply_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_proto_msg_TPInfoReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\025crmOrderService.proto\022\tproto.msg\".\n\tTP" +
                        "Request\022\017\n\007orderID\030\001 \001(\003\022\020\n\010orderKey\030\002 \001" +
                        "(\003\"F\n\013TPInfoReply\022\017\n\007orderID\030\001 \001(\003\022\020\n\010or" +
                        "derKey\030\002 \001(\003\022\024\n\014shopOrderKey\030\003 \001(\t2Q\n\rQa" +
                        "DemoService\022@\n\016QueryTPService\022\024.proto.ms" +
                        "g.TPRequest\032\026.proto.msg.TPInfoReply\"\000B&\n" +
                        "\"org.yefei.qa.mock.grpc.idlP\001b\006p" +
                        "roto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_proto_msg_TPRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_proto_msg_TPRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_msg_TPRequest_descriptor,
                new String[]{"OrderID", "OrderKey",});
        internal_static_proto_msg_TPInfoReply_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_proto_msg_TPInfoReply_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_proto_msg_TPInfoReply_descriptor,
                new String[]{"OrderID", "OrderKey", "ShopOrderKey",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
