// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crmOrderService.proto

package org.apache.skywalking.apm.mock.plugin.grpc.v1.core.idl;

public interface TPRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:proto.msg.TPRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  orderID
     * </pre>
     * <p>
     * <code>optional int64 orderID = 1;</code>
     */
    long getOrderID();

    /**
     * <pre>
     * orderKey
     * </pre>
     * <p>
     * <code>optional int64 orderKey = 2;</code>
     */
    long getOrderKey();
}
